apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI4MDgzLW5leHVzLXNvdGp0Z3JzLnNvbHV0aW9ucy1kZW1vLm9wc2VyYS5pbyI6eyJ1c2VybmFtZSI6Im9wc2VyYS1zb2x1dGlvbnMtZW5naW5lZXJpbmciLCJwYXNzd29yZCI6IlNvbHV0aW9uc0VuZ2luZWVyRG9ja2VyUmVwbyIsImVtYWlsIjoibmF3YXpAb3BzZXJhLmlvIiwiYXV0aCI6ImIzQnpaWEpoTFhOdmJIVjBhVzl1Y3kxbGJtZHBibVZsY21sdVp6cFRiMngxZEdsdmJuTkZibWRwYm1WbGNrUnZZMnRsY2xKbGNHOD0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: java-api-argocd-secret
type: kubernetes.io/dockerconfigjson 
---
apiVersion: v1
kind: Service
metadata:
  name: java-api-argocd
spec:
  selector:
    app: java-api-argocd
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api-argocd
  labels:
    app: java-api-argocd
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  revisionHistoryLimit: 10
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-api-argocd
        octopusexport: OctopusExport
    spec:
      imagePullSecrets:
        - name: java-api-argocd-secret
      containers:
        - name: solutions-engineers-demo
          image: 8083-nexus-sotjtgrs.solutions-demo.opsera.io/solutions-engineers-demo:4
          ports:
            - name: java-api-argocd
              containerPort: 8080